### ISSUE TITLE
CI failures

### ISSUE THREAD

**Issue by pwaller** [mewmew/float#19]
CI seems to have been intermittently failing for a long time. See all the red X's in

https://github.com/mewmew/float/commits/master

**Comment by mewmew** [comment]
From https://travis-ci.org/mewmew/float/jobs/628377883?utm_source=github_status

`go test` pass and takes about 1 minute

`go test -race` times out after 10 minutes (there are a lot of test cases)

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Besides this issue there is also a lint issue, but the above one is the main reason of the CI failures.

```
### golint

float128ppc/float128ppc.go:19:2: comment on exported var NegNaN should be of the form "NegNaN ..."

float128ppc/float128ppc.go:21:2: comment on exported var NaN should be of the form "NaN ..."
```

**Comment by pwaller** [comment]
Kind of raises the question: why `-race` for these test cases?

**Comment by pwaller** [comment]
FWIW, I measure a 35x slowdown with the race detector enabled on these test cases. The Go issue tracker suggests that this order of magnitude slowdown is normal, see: https://github.com/golang/go/issues/22244 - https://github.com/golang/go/issues/22820

But if we're not doing anything thready, then why use the race detector in the first place? :)

**Comment by mewmew** [comment]
> FWIW, I measure a 35x slowdown with the race detector enabled on these test cases.

Good to know. Then the timeout after 10 minutes makes sense. We'd need ~35 minutes to complete the race test.

The ~20x slowdown of golang/go#22820 seems to be "working as intended":
> This is expected, and documented.

> But if we're not doing anything thready, then why use the race detector in the first place? :)

fair point :p

The CI scripts always enable the `go test -race`. I guess we could add a switch to disable them.
